### ISSUE TITLE
add doc tests

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/axohtml#30]
per #29 i think it'd be useful to make sure we are testing not only the library but the docs :)

**Comment by ashleygwilliams** [comment]
there are already doc tests... not sure how we could have caught the previous issues, but i'm gonna close this for now, chalk it up to an awkward transition from a fork, and address it later if it continues to be an issue

**Comment by adrianheine** [comment]
You are running doc tests, but they only linkcheck intra-doc links, they don't check
1. whether you use intra-doc links instead of regular, relative markdown links
2. whether those regular markdown links are broken
3. what happens in your README.md at all

You could use `rustdoc --test README.md` to run the code examples in README.md, but since they don't have `use` clauses they are `use`less (haha) because they never compile.
